# Core services bundle
# Includes: Caddy (reverse proxy), Uptime Kuma (monitoring)

services:
  caddy:
    image: caddy:2-alpine
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    environment:
      - DOMAIN=${DOMAIN:-homelab.local}
      - ACME_EMAIL=${ACME_EMAIL:-admin@example.com}
    volumes:
      - ${PWD}/services/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - homelab

  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    restart: unless-stopped
    environment:
      - TZ=${TZ:-America/New_York}
    volumes:
      - uptime_kuma_data:/app/data
    ports:
      - "3001:3001"
    networks:
      - homelab

volumes:
  caddy_data:
  caddy_config:
  uptime_kuma_data:

networks:
  homelab:
    driver: bridge
