# Media services bundle
# Includes: Jellyfin (media server), qBittorrent with VPN

services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    environment:
      - TZ=${TZ:-America/New_York}
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
    volumes:
      - jellyfin_config:/config
      - jellyfin_cache:/cache
      - ${MEDIA_PATH:-/media}:/media:ro
    ports:
      - "8096:8096"
    networks:
      - homelab

  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER:-mullvad}
      - VPN_TYPE=${VPN_TYPE:-wireguard}
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY:-}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES:-}
    volumes:
      - gluetun_data:/gluetun
    ports:
      - "8085:8085"
    networks:
      - homelab

  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    network_mode: service:gluetun
    depends_on:
      - gluetun
    environment:
      - TZ=${TZ:-America/New_York}
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - WEBUI_PORT=${WEBUI_PORT:-8085}
    volumes:
      - qbittorrent_config:/config
      - ${DOWNLOAD_PATH:-./downloads}:/downloads

volumes:
  jellyfin_config:
  jellyfin_cache:
  gluetun_data:
  qbittorrent_config:

networks:
  homelab:
    external: true
